### PR TITLE
Restrict user searches to students

### PR DESCRIPTION
**Pull request by tkw1536**
After a request from IRC IT, we need to restrict users to students. This PR updates the LDAP Query accpordingly.

### CODE REVIEW

**Comment by tkw1536** [comment]
Rebased onto https://github.com/OpenJUB/dreamjub/pull/56 to make the travis tests pass again.

**Review by kuboschek — APPROVED** [review]
LGTM!

**Comment by tkw1536** [comment]
Had to fix a stupid typo, please re-verify.

**Pull request merged**
